import errno

_optionals = []

# Constants
ZMQ_HAUSNUMERO = 156384712
ZMQ_ENOTSUP = (ZMQ_HAUSNUMERO + 1)
ZMQ_EPROTONOSUPPORT = (ZMQ_HAUSNUMERO + 2)
ZMQ_ENOBUFS = (ZMQ_HAUSNUMERO + 3)
ZMQ_ENETDOWN = (ZMQ_HAUSNUMERO + 4)
ZMQ_EADDRINUSE = (ZMQ_HAUSNUMERO + 5)
ZMQ_EADDRNOTAVAIL = (ZMQ_HAUSNUMERO + 6)
ZMQ_ECONNREFUSED = (ZMQ_HAUSNUMERO + 7)
ZMQ_EINPROGRESS = (ZMQ_HAUSNUMERO + 8)
ZMQ_ENOTSOCK = (ZMQ_HAUSNUMERO + 9)

# Native 0MQ error codes
ZMQ_EFSM = (ZMQ_HAUSNUMERO + 51)
ZMQ_ENOCOMPATPROTO = (ZMQ_HAUSNUMERO + 52)
ZMQ_ETERM = (ZMQ_HAUSNUMERO + 53)
ZMQ_EMTHREAD = (ZMQ_HAUSNUMERO + 54)
ZMQ_MAX_VSM_SIZE = 30

# Message types
ZMQ_DELIMITER = 31
ZMQ_VSM = 32

ZMQ_MSG_MORE = 1
ZMQ_MSG_SHARED = 128
ZMQ_MSG_MASK = 129 # Merges all the flags

# Socket types
ZMQ_PAIR = 0
ZMQ_PUB = 1
ZMQ_SUB = 2
ZMQ_REQ = 3
ZMQ_REP = 4
ZMQ_DEALER = 5
ZMQ_ROUTER = 6
ZMQ_PULL = 7
ZMQ_PUSH = 8
ZMQ_XPUB = 9
ZMQ_XSUB = 10

# TODO Support versions here
ZMQ_XREQ = ZMQ_DEALER        # Old alias, remove in 3.x
ZMQ_XREP = ZMQ_ROUTER        # Old alias, remove in 3.x
ZMQ_UPSTREAM = ZMQ_PULL      # Old alias, remove in 3.x
ZMQ_DOWNSTREAM = ZMQ_PUSH    # Old alias, remove in 3.x

# Socket options
ZMQ_HWM = 1
ZMQ_SWAP = 3
ZMQ_AFFINITY = 4
ZMQ_IDENTITY = 5
ZMQ_SUBSCRIBE = 6
ZMQ_UNSUBSCRIBE = 7
ZMQ_RATE = 8
ZMQ_RECOVERY_IVL = 9
ZMQ_MCAST_LOOP = 10
ZMQ_SNDBUF = 11
ZMQ_RCVBUF = 12
ZMQ_RCVMORE = 13
ZMQ_FD = 14
ZMQ_EVENTS = 15
ZMQ_TYPE = 16
ZMQ_LINGER = 17
ZMQ_RECONNECT_IVL = 18
ZMQ_BACKLOG = 19
ZMQ_RECOVERY_IVL_MSEC = 20   # opt. recovery time, reconcile in 3.x
ZMQ_RECONNECT_IVL_MAX = 21
ZMQ_MAXMSGSIZE = 22
ZMQ_SNDHWM = 23
ZMQ_RCVHWM = 24

# Send/recv options
ZMQ_NOBLOCK = 1
ZMQ_DONTWAIT = 1
ZMQ_SNDMORE = 2

ZMQ_POLLIN = 1
ZMQ_POLLOUT = 2
ZMQ_POLLERR = 4

# Devices
ZMQ_STREAMER = 1
ZMQ_FORWARDER = 2
ZMQ_QUEUE = 3


ENOTSUP = ZMQ_ENOTSUP
EPROTONOSUPPORT = ZMQ_EPROTONOSUPPORT
ENOBUFS = ZMQ_ENOBUFS
ENETDOWN = ZMQ_ENETDOWN
EADDRINUSE = ZMQ_EADDRINUSE
EADDRNOTAVAIL = ZMQ_EADDRNOTAVAIL
ECONNREFUSED = ZMQ_ECONNREFUSED
EINPROGRESS = ZMQ_EINPROGRESS
ENOTSOCK = ZMQ_ENOTSOCK

# Native 0MQ error codes
EFSM = ZMQ_EFSM
ENOCOMPATPROTO = ZMQ_ENOCOMPATPROTO
ETERM = ZMQ_ETERM
EMTHREAD = ZMQ_EMTHREAD
MAX_VSM_SIZE = ZMQ_MAX_VSM_SIZE

# Error handling
EAGAIN = errno.EAGAIN
EINVAL = errno.EINVAL
EFAULT = errno.EFAULT
ENOMEM = errno.ENOMEM
ENODEV = errno.ENODEV

# Message types
DELIMITER = ZMQ_DELIMITER
VSM = ZMQ_VSM

MSG_MORE = ZMQ_MSG_MORE
MSG_SHARED = ZMQ_MSG_SHARED
MSG_MASK = ZMQ_MSG_MASK

# Socket types
PAIR = ZMQ_PAIR
PUB = ZMQ_PUB
SUB = ZMQ_SUB
REQ = ZMQ_REQ
REP = ZMQ_REP
DEALER = ZMQ_DEALER
ROUTER = ZMQ_ROUTER
PULL = ZMQ_PULL
PUSH = ZMQ_PUSH

if ZMQ_VERSION >= 20101:
    XPUB = ZMQ_XPUB
    XSUB = ZMQ_XSUB
    _optionals.extend(['XPUB', 'XSUB'])

XREQ = ZMQ_XREQ
XREP = ZMQ_XREP

if ZMQ_VERSION < 30000:
    UPSTREAM = ZMQ_UPSTREAM
    DOWNSTREAM = ZMQ_DOWNSTREAM
    _optionals.extend(['UPSTREAM', 'DOWNSTREAM'])

AFFINITY = ZMQ_AFFINITY
IDENTITY = ZMQ_IDENTITY
SUBSCRIBE = ZMQ_SUBSCRIBE
UNSUBSCRIBE = ZMQ_UNSUBSCRIBE
RATE = ZMQ_RATE
RECOVERY_IVL = ZMQ_RECOVERY_IVL
SNDBUF = ZMQ_SNDBUF
RCVBUF = ZMQ_RCVBUF
RCVMORE = ZMQ_RCVMORE
FD = ZMQ_FD
EVENTS = ZMQ_EVENTS
TYPE = ZMQ_TYPE
LINGER = ZMQ_LINGER
RECONNECT_IVL = ZMQ_RECONNECT_IVL
BACKLOG = ZMQ_BACKLOG

# sockopt types
sockopts_bytes = [SUBSCRIBE, UNSUBSCRIBE, IDENTITY]
sockopts_int64 = [AFFINITY]
sockopts_int32 = []

# Socket options
if ZMQ_VERSION < 30000:
    HWM = ZMQ_HWM
    SWAP = ZMQ_SWAP
    MCAST_LOOP = ZMQ_MCAST_LOOP
    _optionals.extend(['HWM', 'SWAP', 'MCAST_LOOP'])
    sockopts_int64.extend([HWM, SWAP, MCAST_LOOP])
else:
    SNDHWM = ZMQ_SNDHWM
    RCVHWM = ZMQ_RCVHWM
    MAXMSGSIZE= ZMQ_MAXMSGSIZE
    _optionals.extend(['SNDHWM', 'RCVHWM', 'MAXMSGSIZE'])
    sockopts_int32.extend([SNDHWM, RCVHWM])

if ZMQ_VERSION >= 20101:
    if ZMQ_VERSION < 30000:
        RECOVERY_IVL_MSEC = ZMQ_RECOVERY_IVL_MSEC
        sockopts_int64.append(RECOVERY_IVL_MSEC)
        _optionals.append('RECOVERY_IVL_MSEC')

    RECONNECT_IVL_MAX = ZMQ_RECONNECT_IVL_MAX
    sockopts_int32.append(RECONNECT_IVL_MAX)
    _optionals.append('RECONNECT_IVL_MAX')

switched = [RATE, RECOVERY_IVL, SNDBUF, RCVBUF, RCVMORE]
if ZMQ_VERSION < 30000:
    sockopts_int64.extend(switched)
else:
    sockopts_int32.extend(switched)

# Send/recv options
if ZMQ_VERSION < 30000:
    NOBLOCK = ZMQ_NOBLOCK
else:
    NOBLOCK = ZMQ_DONTWAIT
    DONTWAIT = ZMQ_DONTWAIT
    _optionals.extend(['DONTWAIT'])
SNDMORE = ZMQ_SNDMORE

POLLIN = ZMQ_POLLIN
POLLOUT = ZMQ_POLLOUT
POLLERR = ZMQ_POLLERR

# Devices
STREAMER = ZMQ_STREAMER
FORWARDER = ZMQ_FORWARDER
QUEUE = ZMQ_QUEUE

__all__ = [
    'AFFINITY',
    'BACKLOG',
    'EVENTS',
    'FD',
    'FORWARDER',
    'IDENTITY',
    'LINGER',
    'NOBLOCK',
    'PAIR',
    'POLLERR',
    'POLLIN',
    'POLLOUT',
    'PUB',
    'PULL',
    'PUSH',
    'QUEUE',
    'RATE',
    'RCVBUF',
    'RCVMORE',
    'RECONNECT_IVL',
    'RECOVERY_IVL',
    'REP',
    'REQ',
    'SNDBUF',
    'SNDMORE',
    'STREAMER',
    'SUB',
    'SUBSCRIBE',
    'TYPE',
    'UNSUBSCRIBE',
    'XREP',
    'XREQ',
    # ERRNO codes
    'EADDRINUSE',
    'EADDRNOTAVAIL',
    'EAGAIN',
    'ECONNREFUSED',
    'EFAULT',
    'EFSM',
    'EINPROGRESS',
    'EINVAL',
    'EMTHREAD',
    'ENETDOWN',
    'ENOBUFS',
    'ENOCOMPATPROTO',
    'ENODEV',
    'ENOMEM',
    'ENOTSUP',
    'EPROTONOSUPPORT',
    'ETERM',
    # collections
    'sockopts_bytes',
    'sockopts_int32',
    'sockopts_int64'
]
__all__.extend(_optionals)
del _optionals
